Use '/' instead of '\' in include statement
The use of '\' instead of '/' gives this error in macOS (and I suppose also in Linux):
```
In file included from /Users/username/Documents/Arduino/attiny85-spectrum_32band/attiny85-spectrum_32band.ino:1:0:
/Users/username/Documents/Arduino/libraries/fix_fft/src/fix_fft.h:3:10: fatal error: avr\pgmspace.h: No such file or directory
 #include <avr\pgmspace.h>
          ^~~~~~~~~~~~~~~~
```